## Этап 1 - Подключение библиотек и базовые настройки

На данном этапе мы подключаем все нужные библиотеки для оценки модели случайного леса. Кроме того, мы задаем базовые конфигурации - путь к датасету, random seed для воспроизводимости, количество фолдов для кросс-валидации, размер пространственной сетки для группировки объектов.

---

Кроме этого, явно задаётся список колонок, которые будут использоваться. Это нужно, чтобы:
- контролировать структуру данных
- отсечь лишние или случайные признаки
- гарантировать воспроизводимость эксперимента

In [1]:
import warnings
warnings.filterwarnings("ignore", category=UserWarning)

In [2]:
import numpy as np
import pandas as pd

from shapely import wkb

from sklearn.base import clone
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.metrics import (
    mean_squared_error,
    mean_absolute_error,
    r2_score,
)
from sklearn.model_selection import GroupKFold
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder
from sklearn.ensemble import RandomForestRegressor

from itertools import product
from pathlib import Path

In [3]:
DATA_PATH = Path("../data/interim/merged_buildings_by_geometry.parquet") 
RANDOM_STATE = 42
N_SPLITS = 5
GRID_SIZE = 1000

main_cols = [
    "component_id",
    "match_type",
    "match_confidence",
    "geometry_source",

    "target_height",
    "target_height_is_observed",
    "target_height_source",
    "target_height_source_detail",
    "target_height_reliability",

    "n_a",
    "n_b",
    "uids_a",
    "uids_b",

    "n_edges_ab",
    "max_iou",
    "mean_iou",
    "max_overlap_a",
    "max_overlap_b",
    "min_dist_m",

    "sum_area_a",
    "sum_area_b",
    "union_area_a",
    "union_area_b",
    "union_area_all",

    "n_b_with_height",
    "median_height_b",
    "median_stairs_b",
    "median_avg_floor_height_b",
    "mode_purpose_b",

    "n_neighbors_50m",
    "n_neighbors_obs_height_50m",
    "neighbor_height_mean_50m",
    "neighbor_height_median_50m",
    "neighbor_height_min_50m",
    "neighbor_height_max_50m",
    "neighbor_height_std_50m",
    "neighbor_height_q25_50m",
    "neighbor_height_q75_50m",

    "n_neighbors_100m",
    "n_neighbors_obs_height_100m",
    "neighbor_height_mean_100m",
    "neighbor_height_median_100m",
    "neighbor_height_min_100m",
    "neighbor_height_max_100m",
    "neighbor_height_std_100m",
    "neighbor_height_q25_100m",
    "neighbor_height_q75_100m",

    "rep_geometry",
]

Реализуется функция, которая преобразует геометрию из WKB (бинарный формат) в объект shapely.
Это необходимо для дальнейших пространственных операций.

In [4]:
def load_wkb_geometry(value):
    if value is None or pd.isna(value):
        return None

    if isinstance(value, memoryview):
        value = value.tobytes()
    elif isinstance(value, bytearray):
        value = bytes(value)

    return wkb.loads(value)

## Этап 2 - Построение пространственных групп и предобработка

Для каждого объекта:
- восстанавливается геометрия
- вычисляется центроид
- координаты центроида квантуются в сетку фиксированного размера
- формируется идентификатор группы

Это нужно для того, чтобы использовать GroupKFold и избежать утечки информации между train и test за счёт пространственной близости объектов.

In [5]:
def build_spatial_groups(df, geom_col="rep_geometry", grid_size=1000):
    geoms = df[geom_col].apply(load_wkb_geometry)
    centroids = geoms.apply(lambda g: g.centroid if g is not None else None)

    x = centroids.apply(lambda c: c.x if c is not None else np.nan)
    y = centroids.apply(lambda c: c.y if c is not None else np.nan)

    grid_x = np.floor(x / grid_size).astype("Int64")
    grid_y = np.floor(y / grid_size).astype("Int64")

    groups = grid_x.astype(str) + "_" + grid_y.astype(str)
    return groups, x, y

Для всех признаков вида neighbor_height_*:

- создаётся бинарный индикатор наличия значения (has_*)
- сами пропуски заменяются на 0

In [6]:
def add_neighbor_missing_indicators(df):
    df = df.copy()

    neighbor_stat_cols = [
        c for c in df.columns
        if c.startswith("neighbor_height_")
    ]

    for col in neighbor_stat_cols:
        ind_col = f"has_{col}"
        df[ind_col] = df[col].notna().astype(int)
        df[col] = df[col].fillna(0)

    return df

Реализуется единая функция, которая считает:

- MSE
- RMSE
- MAE
- R²

Это нужно для унифицированной оценки качества модели на каждом фолде.

In [7]:
def compute_metrics(y_true, y_pred):
    mse = mean_squared_error(y_true, y_pred)
    rmse = np.sqrt(mse)
    mae = mean_absolute_error(y_true, y_pred)
    r2 = r2_score(y_true, y_pred)

    return {
        "rmse": rmse,
        "mae": mae,
        "mse": mse,
        "r2": r2,
    }

## Этап 3 - Кросс валидация и формирование наборов признаков

Реализуется процедура обучения и оценки модели:

- используется GroupKFold вместо обычного KFold
- на каждом фолде модель обучается на train и предсказывает на test
- сохраняются метрики

---

Определяются несколько вариантов признаков: 
- базовый (минимальный набор)
- расширенный за счёт агрегатов по A/B
- варианты с соседями (только средние или полный набор статистик)
- полный набор всех признаков.

Это делается для анализа вклада разных групп признаков и выбора оптимального набора.

In [8]:
def cross_validate_with_groups(
    model,
    X,
    y,
    groups,
    n_splits=5,
    return_oof=True,
):
    cv = GroupKFold(n_splits=n_splits)

    fold_rows = []
    oof_pred = np.full(len(X), np.nan, dtype=float)

    for fold, (train_idx, test_idx) in enumerate(cv.split(X, y, groups), start=1):
        X_train = X.iloc[train_idx]
        X_test = X.iloc[test_idx]
        y_train = y.iloc[train_idx]
        y_test = y.iloc[test_idx]

        model_fold = clone(model)
        model_fold.fit(X_train, y_train)
        pred = model_fold.predict(X_test)

        if return_oof:
            oof_pred[test_idx] = pred

        metrics = compute_metrics(y_test, pred)
        metrics["fold"] = fold
        fold_rows.append(metrics)

    folds_df = pd.DataFrame(fold_rows)
    mean_metrics = folds_df[["rmse", "mae", "mse", "r2"]].mean().to_dict()

    return folds_df, mean_metrics, oof_pred

In [9]:
def make_feature_sets():
    baseline = [
        "median_stairs_b",
        "median_avg_floor_height_b",
        "union_area_all",
        "mode_purpose_b",
    ]

    plus_n_ab = baseline + [
        "n_a",
        "n_b",
        "n_b_with_height",
        "n_edges_ab",
    ]

    neighbors_mean = plus_n_ab + [
        "n_neighbors_50m",
        "n_neighbors_obs_height_50m",
        "neighbor_height_mean_50m",
        "has_neighbor_height_mean_50m",
        "n_neighbors_100m",
        "n_neighbors_obs_height_100m",
        "neighbor_height_mean_100m",
        "has_neighbor_height_mean_100m",
    ]

    neighbors_full_50m = plus_n_ab + [
        "n_neighbors_50m",
        "n_neighbors_obs_height_50m",
        "neighbor_height_mean_50m",
        "neighbor_height_median_50m",
        "neighbor_height_min_50m",
        "neighbor_height_max_50m",
        "neighbor_height_std_50m",
        "neighbor_height_q25_50m",
        "neighbor_height_q75_50m",
        "has_neighbor_height_mean_50m",
        "has_neighbor_height_median_50m",
        "has_neighbor_height_min_50m",
        "has_neighbor_height_max_50m",
        "has_neighbor_height_std_50m",
        "has_neighbor_height_q25_50m",
        "has_neighbor_height_q75_50m",
    ]

    neighbors_full_100m = plus_n_ab + [
        "n_neighbors_100m",
        "n_neighbors_obs_height_100m",
        "neighbor_height_mean_100m",
        "neighbor_height_median_100m",
        "neighbor_height_min_100m",
        "neighbor_height_max_100m",
        "neighbor_height_std_100m",
        "neighbor_height_q25_100m",
        "neighbor_height_q75_100m",
        "has_neighbor_height_mean_100m",
        "has_neighbor_height_median_100m",
        "has_neighbor_height_min_100m",
        "has_neighbor_height_max_100m",
        "has_neighbor_height_std_100m",
        "has_neighbor_height_q25_100m",
        "has_neighbor_height_q75_100m",
    ]

    full = [
        "match_type",
        "match_confidence",
        "geometry_source",
        "target_height_reliability",
        "n_a",
        "n_b",
        "n_edges_ab",
        "sum_area_a",
        "sum_area_b",
        "union_area_a",
        "union_area_b",
        "union_area_all",
        "n_b_with_height",
        "median_height_b",
        "median_stairs_b",
        "median_avg_floor_height_b",
        "mode_purpose_b",

        "n_neighbors_50m",
        "n_neighbors_obs_height_50m",
        "neighbor_height_mean_50m",
        "neighbor_height_median_50m",
        "neighbor_height_min_50m",
        "neighbor_height_max_50m",
        "neighbor_height_std_50m",
        "neighbor_height_q25_50m",
        "neighbor_height_q75_50m",

        "n_neighbors_100m",
        "n_neighbors_obs_height_100m",
        "neighbor_height_mean_100m",
        "neighbor_height_median_100m",
        "neighbor_height_min_100m",
        "neighbor_height_max_100m",
        "neighbor_height_std_100m",
        "neighbor_height_q25_100m",
        "neighbor_height_q75_100m",

        "has_neighbor_height_mean_50m",
        "has_neighbor_height_median_50m",
        "has_neighbor_height_min_50m",
        "has_neighbor_height_max_50m",
        "has_neighbor_height_std_50m",
        "has_neighbor_height_q25_50m",
        "has_neighbor_height_q75_50m",

        "has_neighbor_height_mean_100m",
        "has_neighbor_height_median_100m",
        "has_neighbor_height_min_100m",
        "has_neighbor_height_max_100m",
        "has_neighbor_height_std_100m",
        "has_neighbor_height_q25_100m",
        "has_neighbor_height_q75_100m",
    ]

    return {
        "baseline": baseline,
        "plus_n_ab": plus_n_ab,
        "neighbors_mean": neighbors_mean,
        "neighbors_full_50m": neighbors_full_50m,
        "neighbors_full_100m": neighbors_full_100m,
        "full": full,
    }

## Этап 4 - Подготовка к обучению

**Загрузка и первичная фильтрация данных**
- читается parquet-файл
- оставляются только нужные колонки
- выбираются только объекты, где целевая переменная наблюдается.

Таким образом формируется обучающая выборка.

**Удаление служебных метрик матчинга**
Удаляются признаки типа IoU и overlap, которые использовались для слияния данных. Они могут давать утечку или не иметь смысла для финальной модели.

**Добавление индикаторов пропусков** 
Применяется функция обработки neighbor-признаков, чтобы корректно закодировать отсутствие данных.

**Построение spatial_group**
Добавляется колонка группировки, а также координаты центроида. После этого удаляются строки без валидной группы.

In [10]:
df = pd.read_parquet(DATA_PATH)
df = df[main_cols].copy()

df = df[df["target_height_is_observed"] == 1].copy()

drop_match_metric_cols = [
    "max_iou",
    "mean_iou",
    "max_overlap_a",
    "max_overlap_b",
    "min_dist_m",
]
df = df.drop(columns=drop_match_metric_cols)

df = add_neighbor_missing_indicators(df)

df["spatial_group"], df["centroid_x"], df["centroid_y"] = build_spatial_groups(
    df,
    geom_col="rep_geometry",
    grid_size=GRID_SIZE,
)

df = df[df["spatial_group"].notna()].copy()

print(df.shape)
df.head()

(101563, 60)

,component_id,match_type,match_confidence,geometry_source,target_height,target_height_is_observed,target_height_source,target_height_source_detail,target_height_reliability,n_a,...,has_neighbor_height_mean_100m,has_neighbor_height_median_100m,has_neighbor_height_min_100m,has_neighbor_height_max_100m,has_neighbor_height_std_100m,has_neighbor_height_q25_100m,has_neighbor_height_q75_100m,spatial_group,centroid_x,centroid_y
0,1,n:1,high,A,4.50,1,B_observed,B_from_nto1_match,medium,8,...,1,1,1,1,1,1,1,673_6635,673859.539664,6.635505e+06
1,2,n:1,high,A,4.50,1,B_observed,B_from_nto1_match,medium,5,...,1,1,1,1,1,1,1,673_6635,673885.218595,6.635511e+06
2,3,n:n,high,A,60.00,1,B_observed,B_from_nton_match,medium,12,...,1,1,1,1,1,1,1,677_6640,677022.530648,6.640407e+06
5,6,n:n,high,B,48.00,1,B_observed,B_from_nton_match,medium,18,...,1,1,1,1,1,1,1,678_6638,678532.626405,6.638733e+06
6,7,n:n,high,B,68.25,1,B_observed,B_from_nton_match,medium,3,...,1,1,1,1,1,1,1,678_6640,678893.429480,6.640099e+06

## Этап 5 - Построение обучающего пути

**Определение сетки гиперпараметров**
Задаётся набор параметров Random Forest:
- глубина деревьев
- минимальное число объектов в узлах
- количество деревьев
- стратегия выбора признаков

Далее строится полный список комбинаций для перебора. Это необходимо для определения лучшей комбинации. 

Далее фиксируются наборы признаков, целевая переменная, колонка группировки. 

Это завершает подготовку к экспериментам с моделями.

In [11]:
def build_rf_pipeline(feature_cols, rf_params):
    X_sample = df[feature_cols]

    categorical_cols = X_sample.select_dtypes(
            include=["object", "category", "string"]
    ).columns.tolist()
    numeric_cols = [c for c in feature_cols if c not in categorical_cols]

    preprocessor = ColumnTransformer(
        transformers=[
            (
                "num",
                Pipeline([
                    ("imputer", SimpleImputer(strategy="median")),
                ]),
                numeric_cols,
            ),
            (
                "cat",
                Pipeline([
                    ("imputer", SimpleImputer(strategy="most_frequent")),
                    ("ohe", OneHotEncoder(handle_unknown="ignore")),
                ]),
                categorical_cols,
            ),
        ],
        remainder="drop",
    )

    model = RandomForestRegressor(
        random_state=RANDOM_STATE,
        n_jobs=-1,
        **rf_params,
    )

    pipe = Pipeline([
        ("preprocessor", preprocessor),
        ("model", model),
    ])

    return pipe

In [12]:
rf_param_grid = {
    "n_estimators": [300],
    "max_depth": [None, 15],
    "min_samples_split": [2, 10],
    "min_samples_leaf": [1, 5],
    "max_features": ["sqrt"],
}

rf_param_list = [
    dict(zip(rf_param_grid.keys(), values))
    for values in product(*rf_param_grid.values())
]

print(f"Всего комбинаций RF: {len(rf_param_list)}")
rf_param_list[:3]

Всего комбинаций RF: 8

[{'n_estimators': 300,
  'max_depth': None,
  'min_samples_split': 2,
  'min_samples_leaf': 1,
  'max_features': 'sqrt'},
 {'n_estimators': 300,
  'max_depth': None,
  'min_samples_split': 2,
  'min_samples_leaf': 5,
  'max_features': 'sqrt'},
 {'n_estimators': 300,
  'max_depth': None,
  'min_samples_split': 10,
  'min_samples_leaf': 1,
  'max_features': 'sqrt'}]

In [13]:
feature_sets = make_feature_sets()

target_col = "target_height"
group_col = "spatial_group"

print("Наборы признаков:", list(feature_sets.keys()))
print("target_col =", target_col)
print("group_col =", group_col)

Наборы признаков: ['baseline', 'plus_n_ab', 'neighbors_mean', 'neighbors_full_50m', 'neighbors_full_100m', 'full']
target_col = target_height
group_col = spatial_group

In [14]:
rf_results = []
rf_oof_store = {}

y = df[target_col].reset_index(drop=True)
groups = df[group_col].reset_index(drop=True)

for set_name, feature_cols in feature_sets.items():
    print(f"\n===== Feature set: {set_name} =====")

    X = df[feature_cols].reset_index(drop=True)

    for params in rf_param_list:
        print(f"RF params: {params}")

        pipe = build_rf_pipeline(feature_cols, params)

        folds_df, mean_metrics, oof_pred = cross_validate_with_groups(
            model=pipe,
            X=X,
            y=y,
            groups=groups,
            n_splits=N_SPLITS,
            return_oof=True,
        )

        row = {
            "model_type": "random_forest",
            "feature_set": set_name,
            **params,
            **mean_metrics,
        }
        rf_results.append(row)

        run_key = (
            "random_forest",
            set_name,
            tuple(sorted(params.items()))
        )
        rf_oof_store[run_key] = oof_pred

rf_results_df = (
    pd.DataFrame(rf_results)
    .sort_values(["rmse", "mae"], ascending=[True, True])
    .reset_index(drop=True)
)

rf_results_df.head(20)

===== Feature set: baseline =====
RF params: {'n_estimators': 300, 'max_depth': None, 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_features': 'sqrt'}
RF params: {'n_estimators': 300, 'max_depth': None, 'min_samples_split': 2, 'min_samples_leaf': 5, 'max_features': 'sqrt'}
RF params: {'n_estimators': 300, 'max_depth': None, 'min_samples_split': 10, 'min_samples_leaf': 1, 'max_features': 'sqrt'}
RF params: {'n_estimators': 300, 'max_depth': None, 'min_samples_split': 10, 'min_samples_leaf': 5, 'max_features': 'sqrt'}
RF params: {'n_estimators': 300, 'max_depth': 15, 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_features': 'sqrt'}
RF params: {'n_estimators': 300, 'max_depth': 15, 'min_samples_split': 2, 'min_samples_leaf': 5, 'max_features': 'sqrt'}
RF params: {'n_estimators': 300, 'max_depth': 15, 'min_samples_split': 10, 'min_samples_leaf': 1, 'max_features': 'sqrt'}
RF params: {'n_estimators': 300, 'max_depth': 15, 'min_samples_split': 10, 'min_samples_leaf': 5, 'max_features': 'sqrt'}

===== Feature set: plus_n_ab =====
RF params: {'n_estimators': 300, 'max_depth': None, 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_features': 'sqrt'}
RF params: {'n_estimators': 300, 'max_depth': None, 'min_samples_split': 2, 'min_samples_leaf': 5, 'max_features': 'sqrt'}
RF params: {'n_estimators': 300, 'max_depth': None, 'min_samples_split': 10, 'min_samples_leaf': 1, 'max_features': 'sqrt'}
RF params: {'n_estimators': 300, 'max_depth': None, 'min_samples_split': 10, 'min_samples_leaf': 5, 'max_features': 'sqrt'}
RF params: {'n_estimators': 300, 'max_depth': 15, 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_features': 'sqrt'}
RF params: {'n_estimators': 300, 'max_depth': 15, 'min_samples_split': 2, 'min_samples_leaf': 5, 'max_features': 'sqrt'}
RF params: {'n_estimators': 300, 'max_depth': 15, 'min_samples_split': 10, 'min_samples_leaf': 1, 'max_features': 'sqrt'}
RF params: {'n_estimators': 300, 'max_depth': 15, 'min_samples_split': 10, 'min_samples_leaf': 5, 'max_features': 'sqrt'}

===== Feature set: neighbors_mean =====
RF params: {'n_estimators': 300, 'max_depth': None, 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_features': 'sqrt'}
RF params: {'n_estimators': 300, 'max_depth': None, 'min_samples_split': 2, 'min_samples_leaf': 5, 'max_features': 'sqrt'}
RF params: {'n_estimators': 300, 'max_depth': None, 'min_samples_split': 10, 'min_samples_leaf': 1, 'max_features': 'sqrt'}
RF params: {'n_estimators': 300, 'max_depth': None, 'min_samples_split': 10, 'min_samples_leaf': 5, 'max_features': 'sqrt'}
RF params: {'n_estimators': 300, 'max_depth': 15, 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_features': 'sqrt'}
RF params: {'n_estimators': 300, 'max_depth': 15, 'min_samples_split': 2, 'min_samples_leaf': 5, 'max_features': 'sqrt'}
RF params: {'n_estimators': 300, 'max_depth': 15, 'min_samples_split': 10, 'min_samples_leaf': 1, 'max_features': 'sqrt'}
RF params: {'n_estimators': 300, 'max_depth': 15, 'min_samples_split': 10, 'min_samples_leaf': 5, 'max_features': 'sqrt'}

===== Feature set: neighbors_full_50m =====
RF params: {'n_estimators': 300, 'max_depth': None, 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_features': 'sqrt'}
RF params: {'n_estimators': 300, 'max_depth': None, 'min_samples_split': 2, 'min_samples_leaf': 5, 'max_features': 'sqrt'}
RF params: {'n_estimators': 300, 'max_depth': None, 'min_samples_split': 10, 'min_samples_leaf': 1, 'max_features': 'sqrt'}
RF params: {'n_estimators': 300, 'max_depth': None, 'min_samples_split': 10, 'min_samples_leaf': 5, 'max_features': 'sqrt'}
RF params: {'n_estimators': 300, 'max_depth': 15, 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_features': 'sqrt'}
RF params: {'n_estimators': 300, 'max_depth': 15, 'min_samples_split': 2, 'min_samples_leaf': 5, 'max_features': 'sqrt'}
RF params: {'n_estimators': 300, 'max_depth': 15, 'min_samples_split': 10, 'min_samples_leaf': 1, 'max_features': 'sqrt'}
RF params: {'n_estimators': 300, 'max_depth': 15, 'min_samples_split': 10, 'min_samples_leaf': 5, 'max_features': 'sqrt'}

===== Feature set: neighbors_full_100m =====
RF params: {'n_estimators': 300, 'max_depth': None, 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_features': 'sqrt'}
RF params: {'n_estimators': 300, 'max_depth': None, 'min_samples_split': 2, 'min_samples_leaf': 5, 'max_features': 'sqrt'}
RF params: {'n_estimators': 300, 'max_depth': None, 'min_samples_split': 10, 'min_samples_leaf': 1, 'max_features': 'sqrt'}
RF params: {'n_estimators': 300, 'max_depth': None, 'min_samples_split': 10, 'min_samples_leaf': 5, 'max_features': 'sqrt'}
RF params: {'n_estimators': 300, 'max_depth': 15, 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_features': 'sqrt'}
RF params: {'n_estimators': 300, 'max_depth': 15, 'min_samples_split': 2, 'min_samples_leaf': 5, 'max_features': 'sqrt'}
RF params: {'n_estimators': 300, 'max_depth': 15, 'min_samples_split': 10, 'min_samples_leaf': 1, 'max_features': 'sqrt'}
RF params: {'n_estimators': 300, 'max_depth': 15, 'min_samples_split': 10, 'min_samples_leaf': 5, 'max_features': 'sqrt'}

===== Feature set: full =====
RF params: {'n_estimators': 300, 'max_depth': None, 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_features': 'sqrt'}
RF params: {'n_estimators': 300, 'max_depth': None, 'min_samples_split': 2, 'min_samples_leaf': 5, 'max_features': 'sqrt'}
RF params: {'n_estimators': 300, 'max_depth': None, 'min_samples_split': 10, 'min_samples_leaf': 1, 'max_features': 'sqrt'}
RF params: {'n_estimators': 300, 'max_depth': None, 'min_samples_split': 10, 'min_samples_leaf': 5, 'max_features': 'sqrt'}
RF params: {'n_estimators': 300, 'max_depth': 15, 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_features': 'sqrt'}
RF params: {'n_estimators': 300, 'max_depth': 15, 'min_samples_split': 2, 'min_samples_leaf': 5, 'max_features': 'sqrt'}
RF params: {'n_estimators': 300, 'max_depth': 15, 'min_samples_split': 10, 'min_samples_leaf': 1, 'max_features': 'sqrt'}
RF params: {'n_estimators': 300, 'max_depth': 15, 'min_samples_split': 10, 'min_samples_leaf': 5, 'max_features': 'sqrt'}

,model_type,feature_set,n_estimators,max_depth,min_samples_split,min_samples_leaf,max_features,rmse,mae,mse,r2
0,random_forest,full,300,NaN,2,1,sqrt,1.636561,0.318227,3.380322,0.972347
1,random_forest,full,300,NaN,10,1,sqrt,1.708081,0.345715,3.605710,0.970304
2,random_forest,full,300,15.0,2,1,sqrt,1.743179,0.404602,3.684289,0.969478
3,random_forest,full,300,15.0,10,1,sqrt,1.799317,0.421466,3.896605,0.967640
4,random_forest,full,300,NaN,10,5,sqrt,1.803624,0.391391,3.933904,0.967426
5,random_forest,full,300,NaN,2,5,sqrt,1.803624,0.391391,3.933904,0.967426
6,random_forest,full,300,15.0,2,5,sqrt,1.871523,0.442927,4.163355,0.965285
7,random_forest,full,300,15.0,10,5,sqrt,1.871523,0.442927,4.163355,0.965285
8,random_forest,baseline,300,15.0,2,1,sqrt,2.646006,0.383584,7.564654,0.933200
9,random_forest,baseline,300,15.0,10,1,sqrt,2.646231,0.386005,7.564203,0.933245
10,random_forest,neighbors_mean,300,NaN,2,1,sqrt,2.814282,0.575812,8.431652,0.925784
11,random_forest,neighbors_full_100m,300,NaN,2,1,sqrt,2.823001,0.599259,8.469123,0.925414
12,random_forest,plus_n_ab,300,15.0,10,1,sqrt,2.824664,0.558459,8.459269,0.925132
13,random_forest,neighbors_mean,300,NaN,10,1,sqrt,2.834991,0.606454,8.555121,0.924736
14,random_forest,neighbors_full_100m,300,NaN,10,1,sqrt,2.840192,0.624029,8.576062,0.924549
15,random_forest,baseline,300,15.0,2,5,sqrt,2.842735,0.554588,8.575816,0.924154
16,random_forest,baseline,300,15.0,10,5,sqrt,2.842735,0.554588,8.575816,0.924154
17,random_forest,baseline,300,NaN,10,1,sqrt,2.848406,0.352184,8.622198,0.923088
18,random_forest,baseline,300,NaN,2,5,sqrt,2.849964,0.529314,8.607753,0.923877
19,random_forest,baseline,300,NaN,10,5,sqrt,2.849964,0.529314,8.607753,0.923877

In [15]:
best_rf_row = rf_results_df.iloc[0].to_dict()
best_rf_row

{'model_type': 'random_forest',
 'feature_set': 'full',
 'n_estimators': 300,
 'max_depth': nan,
 'min_samples_split': 2,
 'min_samples_leaf': 1,
 'max_features': 'sqrt',
 'rmse': 1.6365606168809426,
 'mae': 0.3182267260201302,
 'mse': 3.3803220098241957,
 'r2': 0.9723466547868871}

## Объяснение результатов

Лучшие строки — это feature_set = full:
- RMSE ≈ 1.64
- MAE ≈ 0.32
- R² ≈ 0.972

Фактически модель объясняет ~97% дисперсии высоты. 

---

Разница между конфигурациями Random Forest внутри одного набора признаков минимальна:

- max_depth = None vs 15 - почти не влияет
- min_samples_split (2 vs 10) - слабое влияние
- min_samples_leaf (1 vs 5) - немного ухудшает

**Вывод**: модель не упирается в гиперпараметры, а упирается в признаки

---

Эксперимент показывает, что:
- качество модели определяется не архитектурой, а признаками
- текущие соседские признаки не дают пользы
- лучший результат достигается за счёт признаков, вероятно содержащих информацию, близкую к таргету